apiVersion: v1
kind: Namespace
metadata:
  name: codeguardian
  labels:
    name: codeguardian
    environment: production
    app: codeguardian-ai
    version: v1.0.0
  annotations:
    description: "CodeGuardian AI - Autonomous DevSecOps Orchestration Platform"
    contact: "engineering@codeguardian.ai"
    created-by: "manus-ai"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: codeguardian-quota
  namespace: codeguardian
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    secrets: "30"
    configmaps: "30"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: codeguardian-limits
  namespace: codeguardian
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
    type: Container

