apiVersion: v1
kind: Secret
metadata:
  name: codeguardian-secrets
  namespace: codeguardian-ai
  labels:
    app: codeguardian-ai
type: Opaque
data:
  # Base64 encoded secrets - Replace with actual values
  # Use: echo -n "your-secret" | base64
  
  # Application secrets
  secret-key: Y29kZWd1YXJkaWFuLXNlY3JldC1rZXktMzItY2hhcnMtbWluaW11bQ==
  jwt-secret-key: and0LXNlY3JldC1rZXktMzItY2hhcnMtbWluaW11bS1mb3Itand0
  
  # Database connection
  database-url: cG9zdGdyZXNxbDovL2NvZGVndWFyZGlhbjpzZWN1cmVwYXNzd29yZEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvY29kZWd1YXJkaWFuX2Ri
  
  # Redis connection  
  redis-url: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkvMA==
  
  # External API keys (if needed)
  openai-api-key: ""
  github-token: ""
  
  # Encryption keys
  fernet-key: ""
  
  # SMTP configuration (if needed)
  smtp-username: ""
  smtp-password: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: codeguardian-ai
  labels:
    app: postgres
type: Opaque
data:
  # PostgreSQL credentials
  postgres-user: Y29kZWd1YXJkaWFu
  postgres-password: c2VjdXJlcGFzc3dvcmQ=
  postgres-db: Y29kZWd1YXJkaWFuX2Ri

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: codeguardian-ai
  labels:
    app: redis
type: Opaque
data:
  # Redis password
  redis-password: cmVkaXNzZWN1cmVwYXNzd29yZA==

---
# TLS Certificate Secret (replace with actual certificate)
apiVersion: v1
kind: Secret
metadata:
  name: codeguardian-tls
  namespace: codeguardian-ai
  labels:
    app: codeguardian-ai
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...

---
# Docker registry secret (if using private registry)
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: codeguardian-ai
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJteXJlZ2lzdHJ5LmNvbSI6eyJ1c2VybmFtZSI6Im15dXNlciIsInBhc3N3b3JkIjoibXlwYXNzd29yZCIsImVtYWlsIjoibXllbWFpbEBleGFtcGxlLmNvbSIsImF1dGgiOiJiWGwxYzJWeU9tMTVjR0Z6YzNkdmNtUT0ifX19

